name: APA_venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - anyio
  - argon2-cffi
  - asttokens
  - async-lru
  - attrs
  - babel
  - beautifulsoup4
  - bleach
  - bottleneck
  - brotli-python
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - colorama
  - comm
  - contourpy
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - exceptiongroup
  - executing
  - fonttools
  - freetype
  - h11
  - httpcore
  - httpx
  - icu
  - ipykernel
  - ipython
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jsonschema-specifications
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libclang13
  - libdeflate
  - libffi
  - libiconv
  - libpng
  - libpq
  - libsodium
  - libtiff
  - libwebp-base
  - libxml2
  - libxslt
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-inline
  - minizip
  - mistune
  - nbclient
  - nbconvert-core
  - nbformat
  - nest-asyncio
  - notebook
  - notebook-shim
  - numexpr
  - numpy
  - openjpeg
  - openssl
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - parso
  - patsy
  - pillow
  - platformdirs
  - prometheus_client
  - prompt-toolkit
  - psutil
  - pure_eval
  - pycparser
  - pyparsing
  - pyside6
  - pysocks
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - pytz
  - pyyaml
  - pyzmq
  - qhull
  - qtbase
  - qtdeclarative
  - qtshadertools
  - qtsvg
  - qttools
  - qtwebchannel
  - qtwebengine
  - qtwebsockets
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - statsmodels
  - tbb
  - terminado
  - threadpoolctl
  - tinycss2
  - tk
  - tomli
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - unicodedata2
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - xz
  - yaml
  - zeromq
  - zlib
  - zstd
  - pip:
      - absl-py==2.2.1
      - astunparse==1.6.3
      - charset-normalizer==3.4.1
      - flatbuffers==25.2.10
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - h5py==3.13.0
      - idna==3.10
      - keras==3.9.1
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - namex==0.0.8
      - numpy==2.1.3
      - opt-einsum==3.4.0
      - optree==0.14.1
      - protobuf==5.29.4
      - pygments==2.19.1
      - rich==13.9.4
      - six==1.17.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.0
      - termcolor==2.5.0
      - typing-extensions==4.13.0
      - werkzeug==3.1.3
      - wrapt==1.17.2